#!/bin/bash
#
# Runs the mutation coverage goal for PIT

# This method runs plain PIT
function plain_pit() {
  # Run PIT
  mvn clean install
  mvn org.pitest:pitest-maven:mutationCoverage
  # Archive the PIT report
  dirname=${PWD##*/}
  mv target/pit-reports/* ../${dirname}-pit-reports/
}

# This method runs PIT with a single parameter
function focused_pit() {
  # Comment out all @Test tags, and add them in again for the class
  # whose name is provided.
  find . -type f -name "*.java" -exec sed -i 's/@Test/\/\/ @Test/g' {} +
  find . -type f -name "$1.java" -exec sed -i 's/\/\/ @Test/@Test/g' {} +
  # Run PIT
  mvn clean install
  mvn org.pitest:pitest-maven:mutationCoverage
  # Comment in all @Test tags again (also if proceeded by multiple
  # comment prefixes).
  find . -type f -name "*.java" -exec sed -i 's/\(\/\/ \)\+@Test/@Test/g' {} +
  # Archive the PIT report
  dirname=${PWD##*/}
  mkdir -p ../${dirname}-pit-reports/$1
  mv target/pit-reports/* ../${dirname}-pit-reports/$1
}

if [ "$#" -eq 0 ]
then
  plain_pit
else
  for arg in "$@"
  do
    focused_pit "$arg"
  done
fi
